module.exports = {
    STATUS_ID:[
      {'status_id':-1,'description': 'Huỷ đơn hàng'},
      {'status_id':1,'description': 'Chưa tiếp nhận'},
      {'status_id':2,'description': 'Đã tiếp nhận'},
      {'status_id':3,'description': 'Đã lấy hàng/ Đã nhập kho'},
      {'status_id':4,'description': 'Đã điều phối giao hàng/Đang giao hàng'},
      {'status_id':5,'description': 'Đã giao hàng/ Chưa đối soát'},
      {'status_id':6,'description': 'Đã đối soát'},
      {'status_id':7,'description': 'Không lấy được hàng'},
      {'status_id':8,'description': 'Hoãn lấy hàng'},
      {'status_id':9,'description': 'Không giao được hàng'},
      {'status_id':10,'description': 'Delay giao hàng'},
      {'status_id':11,'description': 'Đã đối soát công nợ trả tháng'},
      {'status_id':12,'description': 'Đã điều phối lấy hàng/ Đang lấy hàng'},
      {'status_id':13,'description': 'Đơn hàng bồi hoàn'},
      {'status_id':20,'description': 'Đang trả hàng (COD cầm hàng đi trả)'},
      {'status_id':21,'description': 'Đã trả hàng (COD đã trả hàng xong)'},
      {'status_id':123,'description': 'Shipper báo đã lấy hàng'},
      {'status_id':127,'description': 'Shipeer báo không lấy được hàng'},
      {'status_id':128,'description': 'Shipper báo delay lấy hàng'},
      {'status_id':45,'description': 'Shipper báo đã giao hàng'},
      {'status_id':49,'description': 'Shipper báo không giao được hàng'},
      {'status_id':410,'description': 'Shipper báo delay giao hàng'},
    ],
    REASON_CODE:[
      {'reason_code':100,'description': 'Nhà cung cấp (NCC) hẹn lấy vào ca tiếp theo'},
      {'reason_code':101,'description': 'GHTK không liên lạc được với NCC'},
      {'reason_code':102,'description': 'NCC chưa có hàng'},
      {'reason_code':103,'description': 'NCC đổi địa chỉ'},
      {'reason_code':104,'description': 'NCC hẹn ngày lấy hàng'},
      {'reason_code':105,'description': 'GHTK quá tải, không lấy kịp'},
      {'reason_code':106,'description': 'Do điều kiện thời tiết, khách quan'},
      {'reason_code':107,'description': 'Lý do khác'},
      {'reason_code':110,'description': 'Địa chỉ ngoài vùng phục vụ'},
      {'reason_code':111,'description': 'Hàng không nhận vận chuyển'},
      {'reason_code':112,'description': 'NCC báo hủy'},
      {'reason_code':113,'description': 'NCC hoãn/không liên lạc được 3 lần'},
      {'reason_code':114,'description': 'Lý do khác'},
      {'reason_code':115,'description': 'Đối tác hủy đơn qua API'},
      {'reason_code':120,'description': 'GHTK quá tải, giao không kịp'},
      {'reason_code':121,'description': 'Người nhận hàng hẹn giao ca tiếp theo'},
      {'reason_code':122,'description': 'Không gọi được cho người nhận hàng'},
      {'reason_code':123,'description': 'Người nhận hàng hẹn ngày giao'},
      {'reason_code':124,'description': 'Người nhận hàng chuyển địa chỉ nhận mới'},
      {'reason_code':125,'description': 'Địa chỉ người nhận sai, cần NCC check lại'},
      {'reason_code':126,'description': 'Do điều kiện thời tiết, khách quan'},
      {'reason_code':127,'description': 'Lý do khác'},
      {'reason_code':128,'description': 'Đối tác hẹn thời gian giao hàng'},
      {'reason_code':129,'description': 'Không tìm thấy hàng'},
      {'reason_code':1200,'description': 'SĐT người nhận sai, cần NCC check lại'},
      {'reason_code':130,'description': 'Người nhận không đồng ý nhận sản phẩm'},
      {'reason_code':131,'description': 'Không liên lạc được với KH 3 lần'},
      {'reason_code':132,'description': 'KH hẹn giao lại quá 3 lần'},
      {'reason_code':133,'description': 'Shop báo hủy đơn hàng'},
      {'reason_code':134,'description': 'Lý do khác'},
      {'reason_code':135,'description': 'Đối tác hủy đơn qua API'},
      {'reason_code':140,'description': 'NCC hẹn trả ca sau'},
      {'reason_code':141,'description': 'Không liên lạc được với NCC'},
      {'reason_code':142,'description': 'NCC không có nhà'},
      {'reason_code':143,'description': 'NCC hẹn ngày trả'},
      {'reason_code':144,'description': 'Lý do khác'},
      {'reason_code':300,'description': 'Lý do khác'},
      {'reason_code':2,'description': 'Lý do khác'}
    ]
  }
  